const { generateCaseAccess, validateCaseAccess } = require('./src/intake/generateCaseAccess')
const { scoreCase } = require('./src/intake/scoreCase')
const { routeCase, reassignCase } = require('./src/intake/routeCase')
const { getCaseThread, postReporterMessage, postInvestigatorMessage } = require('./src/intake/caseThread')
const { aiFollowUp } = require('./src/intake/aiFollowUp')
const { generateChecklist, updateChecklistItem } = require('./src/intake/generateChecklist')
const { storeReferenceCase } = require('./src/consistency/storeReferenceCase')
const { checkConsistency } = require('./src/consistency/checkConsistency')
const { generateReport } = require('./src/intake/generateReport')
const { scheduleDeadlines } = require('./src/compliance/scheduleDeadlines')
const { checkOverdueDeadlines } = require('./src/compliance/checkOverdueDeadlines')
const { proposeAction, closeCase, reviewConsistencyFlag } = require('./src/investigation/caseActions')
const { syncCaseMetadata } = require('./src/intake/syncCaseMetadata')
const { syncCompanyStats } = require('./src/company/syncCompanyStats')
const { inviteStaff } = require('./src/staff/inviteStaff')
const { createCompanyAdmin } = require('./src/company/createCompanyAdmin')
const { acceptInvite } = require('./src/staff/acceptInvite')
const { submitPulseResponse, analyzePulseResponse } = require('./src/intake/analyzePulseResponse')
const { schedulePulseChecks } = require('./src/intake/schedulePulseChecks')
const { registerPushSubscription, sendCaseUpdate } = require('./src/notifications/sendCaseUpdate')

exports.generateCaseAccess = generateCaseAccess
exports.validateCaseAccess = validateCaseAccess
exports.scoreCase = scoreCase
exports.routeCase = routeCase
exports.reassignCase = reassignCase
exports.getCaseThread = getCaseThread
exports.postReporterMessage = postReporterMessage
exports.postInvestigatorMessage = postInvestigatorMessage
exports.aiFollowUp = aiFollowUp
exports.generateChecklist = generateChecklist
exports.updateChecklistItem = updateChecklistItem
exports.storeReferenceCase = storeReferenceCase
exports.checkConsistency = checkConsistency
exports.generateReport = generateReport
exports.scheduleDeadlines = scheduleDeadlines
exports.checkOverdueDeadlines = checkOverdueDeadlines
exports.proposeAction = proposeAction
exports.closeCase = closeCase
exports.reviewConsistencyFlag = reviewConsistencyFlag
exports.syncCaseMetadata = syncCaseMetadata
exports.syncCompanyStats = syncCompanyStats
exports.inviteStaff = inviteStaff
exports.createCompanyAdmin = createCompanyAdmin
exports.acceptInvite = acceptInvite
exports.submitPulseResponse = submitPulseResponse
exports.analyzePulseResponse = analyzePulseResponse
exports.schedulePulseChecks = schedulePulseChecks
exports.registerPushSubscription = registerPushSubscription
exports.sendCaseUpdate = sendCaseUpdate
