const { validateCaseAccess } = require('./src/intake/generateCaseAccess')
const { submitCase } = require('./src/intake/submitCase')
const { createCaseOnBehalf } = require('./src/intake/createCaseOnBehalf')
const { scoreCase } = require('./src/intake/scoreCase')
const { routeCase, reassignCase } = require('./src/intake/routeCase')
const { getCaseThread, postReporterMessage, postInvestigatorMessage } = require('./src/intake/caseThread')
const {
  requestEvidenceUploadUrl,
  requestEvidenceDownloadUrl,
} = require('./src/intake/evidenceAccess')
const { aiFollowUp } = require('./src/intake/aiFollowUp')
const { generateChecklist, updateChecklistItem } = require('./src/intake/generateChecklist')
const { storeReferenceCase } = require('./src/consistency/storeReferenceCase')
const { checkConsistency } = require('./src/consistency/checkConsistency')
const { detectPatterns } = require('./src/patterns/detectPatterns')
const { generateReport } = require('./src/intake/generateReport')
const { scheduleDeadlines } = require('./src/compliance/scheduleDeadlines')
const { checkOverdueDeadlines } = require('./src/compliance/checkOverdueDeadlines')
const { proposeAction, closeCase, reviewConsistencyFlag } = require('./src/investigation/caseActions')
const { getCaseForTriage } = require('./src/investigation/getCaseForTriage')
const { syncCaseMetadata } = require('./src/intake/syncCaseMetadata')
const { syncCompanyStats } = require('./src/company/syncCompanyStats')
const { inviteStaff } = require('./src/staff/inviteStaff')
const { createCompanyAdmin } = require('./src/company/createCompanyAdmin')
const { resolveCompanySlug } = require('./src/company/resolveCompanySlug')
const { acceptInvite } = require('./src/staff/acceptInvite')
const { submitPulseResponse, analyzePulseResponse } = require('./src/intake/analyzePulseResponse')
const { validatePulseInvite } = require('./src/intake/pulseInvites')
const { schedulePulseChecks } = require('./src/intake/schedulePulseChecks')
const { sendPulseChecksNow } = require('./src/intake/sendPulseChecksNow')
const { registerPushSubscription, sendCaseUpdate } = require('./src/notifications/sendCaseUpdate')
const { deliverNotifications } = require('./src/notifications/deliverNotifications')
const { scheduleFollowUps } = require('./src/followup/scheduleFollowUps')
const { runFollowUps } = require('./src/followup/runFollowUps')
const { submitFollowUpResponse } = require('./src/followup/submitFollowUpResponse')

exports.submitCase = submitCase
exports.createCaseOnBehalf = createCaseOnBehalf
exports.validateCaseAccess = validateCaseAccess
exports.scoreCase = scoreCase
exports.routeCase = routeCase
exports.reassignCase = reassignCase
exports.getCaseThread = getCaseThread
exports.postReporterMessage = postReporterMessage
exports.postInvestigatorMessage = postInvestigatorMessage
exports.requestEvidenceUploadUrl = requestEvidenceUploadUrl
exports.requestEvidenceDownloadUrl = requestEvidenceDownloadUrl
exports.aiFollowUp = aiFollowUp
exports.generateChecklist = generateChecklist
exports.updateChecklistItem = updateChecklistItem
exports.storeReferenceCase = storeReferenceCase
exports.checkConsistency = checkConsistency
exports.detectPatterns = detectPatterns
exports.generateReport = generateReport
exports.scheduleDeadlines = scheduleDeadlines
exports.checkOverdueDeadlines = checkOverdueDeadlines
exports.proposeAction = proposeAction
exports.closeCase = closeCase
exports.reviewConsistencyFlag = reviewConsistencyFlag
exports.getCaseForTriage = getCaseForTriage
exports.syncCaseMetadata = syncCaseMetadata
exports.syncCompanyStats = syncCompanyStats
exports.inviteStaff = inviteStaff
exports.createCompanyAdmin = createCompanyAdmin
exports.resolveCompanySlug = resolveCompanySlug
exports.acceptInvite = acceptInvite
exports.submitPulseResponse = submitPulseResponse
exports.validatePulseInvite = validatePulseInvite
exports.analyzePulseResponse = analyzePulseResponse
exports.schedulePulseChecks = schedulePulseChecks
exports.sendPulseChecksNow = sendPulseChecksNow
exports.registerPushSubscription = registerPushSubscription
exports.sendCaseUpdate = sendCaseUpdate
exports.deliverNotifications = deliverNotifications
exports.scheduleFollowUps = scheduleFollowUps
exports.runFollowUps = runFollowUps
exports.submitFollowUpResponse = submitFollowUpResponse
