import {
  signInWithEmailAndPassword,
  signOut,
  sendPasswordResetEmail,
  verifyPasswordResetCode,
  confirmPasswordReset,
} from 'firebase/auth'
import { httpsCallable } from 'firebase/functions'
import { doc, getDoc } from 'firebase/firestore'
import { auth, functions, firestore } from './firebase'

const SUPER_ADMINS_COLLECTION = 'superAdmins'

const acceptInviteCallable = httpsCallable(functions, 'acceptInvite')

export async function signIn(email, password) {
  const credential = await signInWithEmailAndPassword(auth, email.trim(), password)
  return credential.user
}

export async function signOutUser() {
  await signOut(auth)
}

export async function sendPasswordReset(email) {
  await sendPasswordResetEmail(auth, email.trim())
}

// Invite links are Firebase password-reset action codes - the invite email
// itself is generated by admin.auth().generatePasswordResetLink() in
// functions/src/staff/inviteStaff.js, not a custom Firestore token. Firebase
// already rejects an expired or already-used code (auth/expired-action-code,
// auth/invalid-action-code), which is what powers AcceptInvitePage's
// expired/used-link error state without any extra Firestore lookup.
export async function verifyInviteCode(oobCode) {
  return verifyPasswordResetCode(auth, oobCode)
}

export async function acceptInvite(oobCode, newPassword) {
  await confirmPasswordReset(auth, oobCode, newPassword)
}

// Flips the invited staff doc to 'active' (functions/src/staff/acceptInvite.js)
// now that the invitee is signed in with their new password. Only callable
// by the authenticated owner of that staff doc - the function re-checks
// request.auth server-side, this is not a client-side-only gate.
//
// The function reads companyId off request.auth.token, so the call is worthless
// without a current ID token that actually carries the claim. Two things can
// leave the SDK holding one that doesn't: the token cached from a sign-in that
// raced the auth instance finishing its own initialization, and (for an account
// whose claims were stamped after its last sign-in) a token minted before the
// stamp. A forced refresh fixes both, so an 'unauthenticated' answer is retried
// exactly once behind getIdToken(true) rather than surfaced immediately - the
// retry is against the server's own verdict, not a blind one, and a second
// failure propagates.
export async function markInviteAccepted() {
  try {
    const result = await acceptInviteCallable()
    return result.data
  } catch (err) {
    if (err?.code !== 'functions/unauthenticated' || !auth.currentUser) {
      throw err
    }
    await auth.currentUser.getIdToken(true)
    const result = await acceptInviteCallable()
    return result.data
  }
}

// True when Firebase rejected an action code because it is expired or already
// consumed. confirmPasswordReset burns the invite's oobCode, so a user who gets
// past that step and then trips on a later one cannot retry the form: the
// second attempt fails here instead. AcceptInvitePage uses this to tell "the
// link is spent" apart from "the password could not be set", which need
// opposite advice (sign in vs. try again).
export function isSpentActionCode(err) {
  return err?.code === 'auth/expired-action-code' || err?.code === 'auth/invalid-action-code'
}

// Role + companyId live only in Firebase Auth custom claims (stamped by
// inviteStaff.js), never a Firestore field - matches firestore.rules' trust
// boundary. Pass forceRefresh after an action that just changed claims.
export async function getUserClaims(user, forceRefresh = false) {
  const tokenResult = await user.getIdTokenResult(forceRefresh)
  // `departments` is the Manager pulse-visibility scope (an array of department
  // name strings). Read off the ID token here, never a Firestore lookup, so the
  // manager pulse query can carry a matching where('department','in',...) that
  // firestore.rules requires. Absent for every non-manager role; defaulted to
  // [] so a manager with no claim fails closed (sees no departments) rather than
  // reading as "unset".
  //
  // `customRoleId` is the composable-role counterpart of `role` - a staff
  // account carries exactly one of the two (see
  // functions/src/utils/permissionResolver.js). It names a
  // companies/{companyId}/customRoles doc; its permissions are resolved
  // separately (src/utils/permissions.js / AuthContext), never cached here,
  // so editing a custom role's permissions takes effect without a token
  // refresh.
  return {
    role: tokenResult.claims.role ?? null,
    companyId: tokenResult.claims.companyId ?? null,
    departments: Array.isArray(tokenResult.claims.departments) ? tokenResult.claims.departments : [],
    customRoleId: tokenResult.claims.customRoleId ?? null,
  }
}

// Super admin status is an allowlist doc at superAdmins/{uid}, not a custom
// claim - entries are added by hand via functions/scripts/addSuperAdmin.js.
// firestore.rules only lets a signed-in user read their own doc, so this
// must be called with that user's own uid.
export async function checkSuperAdmin(uid) {
  const snapshot = await getDoc(doc(firestore, SUPER_ADMINS_COLLECTION, uid))
  return snapshot.exists()
}
