import {
  signInWithEmailAndPassword,
  signOut,
  sendPasswordResetEmail,
  verifyPasswordResetCode,
  confirmPasswordReset,
} from 'firebase/auth'
import { httpsCallable } from 'firebase/functions'
import { doc, getDoc } from 'firebase/firestore'
import { auth, functions, firestore } from './firebase'

const SUPER_ADMINS_COLLECTION = 'superAdmins'

const acceptInviteCallable = httpsCallable(functions, 'acceptInvite')

export async function signIn(email, password) {
  const credential = await signInWithEmailAndPassword(auth, email.trim(), password)
  return credential.user
}

export async function signOutUser() {
  await signOut(auth)
}

export async function sendPasswordReset(email) {
  await sendPasswordResetEmail(auth, email.trim())
}

// Invite links are Firebase password-reset action codes - the invite email
// itself is generated by admin.auth().generatePasswordResetLink() in
// functions/src/staff/inviteStaff.js, not a custom Firestore token. Firebase
// already rejects an expired or already-used code (auth/expired-action-code,
// auth/invalid-action-code), which is what powers AcceptInvitePage's
// expired/used-link error state without any extra Firestore lookup.
export async function verifyInviteCode(oobCode) {
  return verifyPasswordResetCode(auth, oobCode)
}

export async function acceptInvite(oobCode, newPassword) {
  await confirmPasswordReset(auth, oobCode, newPassword)
}

// Flips the invited staff doc to 'active' (functions/src/staff/acceptInvite.js)
// now that the invitee is signed in with their new password. Only callable
// by the authenticated owner of that staff doc - the function re-checks
// request.auth server-side, this is not a client-side-only gate.
export async function markInviteAccepted() {
  const result = await acceptInviteCallable()
  return result.data
}

// Role + companyId live only in Firebase Auth custom claims (stamped by
// inviteStaff.js), never a Firestore field - matches firestore.rules' trust
// boundary. Pass forceRefresh after an action that just changed claims.
export async function getUserClaims(user, forceRefresh = false) {
  const tokenResult = await user.getIdTokenResult(forceRefresh)
  // `departments` is the Manager pulse-visibility scope (an array of department
  // name strings). Read off the ID token here, never a Firestore lookup, so the
  // manager pulse query can carry a matching where('department','in',...) that
  // firestore.rules requires. Absent for every non-manager role; defaulted to
  // [] so a manager with no claim fails closed (sees no departments) rather than
  // reading as "unset".
  //
  // `customRoleId` is the composable-role counterpart of `role` - a staff
  // account carries exactly one of the two (see
  // functions/src/utils/permissionResolver.js). It names a
  // companies/{companyId}/customRoles doc; its permissions are resolved
  // separately (src/utils/permissions.js / AuthContext), never cached here,
  // so editing a custom role's permissions takes effect without a token
  // refresh.
  return {
    role: tokenResult.claims.role ?? null,
    companyId: tokenResult.claims.companyId ?? null,
    departments: Array.isArray(tokenResult.claims.departments) ? tokenResult.claims.departments : [],
    customRoleId: tokenResult.claims.customRoleId ?? null,
  }
}

// Super admin status is an allowlist doc at superAdmins/{uid}, not a custom
// claim - entries are added by hand via functions/scripts/addSuperAdmin.js.
// firestore.rules only lets a signed-in user read their own doc, so this
// must be called with that user's own uid.
export async function checkSuperAdmin(uid) {
  const snapshot = await getDoc(doc(firestore, SUPER_ADMINS_COLLECTION, uid))
  return snapshot.exists()
}
