const PDFDocument = require('pdfkit')

// Distinct from CLASSIFICATION_BANNER in functions/src/reports/renderReportPdf.js
// on purpose: that banner marks a document containing case narrative and is
// the reason a closed-case report needs the same access-control review as the
// case itself. This document contains neither - only aggregate counts,
// medians and rates - so it carries a banner that says exactly that, which is
// what makes it safe to hand to a board member or auditor without a second
// review of who is allowed to see it.
const CLASSIFICATION_BANNER = 'COMPANY CONFIDENTIAL - AGGREGATE STATISTICS ONLY, NO CASE-LEVEL DETAIL'

const FONT_REGULAR = 'Helvetica'
const FONT_BOLD = 'Helvetica-Bold'
const FONT_ITALIC = 'Helvetica-Oblique'

const COLORS = {
  ink: '#1a1f2b',
  muted: '#5b6472',
  line: '#c7ccd6',
  classification: '#1f4d3a',
}

const PAGE_MARGIN = 50
const FOOTER_HEIGHT = 34

const CATEGORY_LABELS = {
  harassment: 'Harassment',
  toxicManagement: 'Toxic management',
  retaliation: 'Retaliation',
  burnout: 'Burnout',
}

function humanize(value) {
  if (typeof value !== 'string') return value
  return CATEGORY_LABELS[value] ?? value.replace(/_/g, ' ')
}

function formatTimestamp(ms) {
  if (!ms) return '-'
  const iso = new Date(ms).toISOString()
  return `${iso.slice(0, 10)} ${iso.slice(11, 19)} UTC`
}

function formatPercent(value) {
  return value == null ? '-' : `${value}%`
}

function contentWidth(doc) {
  return doc.page.width - doc.page.margins.left - doc.page.margins.right
}

function ensureRoom(doc, height) {
  const bottom = doc.page.height - doc.page.margins.bottom
  if (doc.y + height > bottom) doc.addPage()
}

function sectionHeading(doc, title) {
  ensureRoom(doc, 44)
  doc.moveDown(0.9)
  const width = contentWidth(doc)
  doc.font(FONT_BOLD).fontSize(13).fillColor(COLORS.ink).text(title, { width })
  doc
    .moveTo(doc.page.margins.left, doc.y + 3)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y + 3)
    .strokeColor(COLORS.line)
    .lineWidth(1)
    .stroke()
  doc.moveDown(0.7)
  doc.font(FONT_REGULAR).fontSize(10).fillColor(COLORS.ink)
}

function emptyState(doc, text) {
  ensureRoom(doc, 20)
  doc.font(FONT_ITALIC).fontSize(10).fillColor(COLORS.muted).text(text, { width: contentWidth(doc) })
  doc.moveDown(0.5)
}

function keyValue(doc, label, value) {
  const width = contentWidth(doc)
  const text = value === null || value === undefined || value === '' ? '-' : String(value)

  doc.font(FONT_BOLD).fontSize(8.5)
  const labelHeight = doc.heightOfString(label.toUpperCase(), { width })
  doc.font(FONT_REGULAR).fontSize(10)
  const valueHeight = doc.heightOfString(text, { width })

  ensureRoom(doc, labelHeight + valueHeight + 10)
  doc.font(FONT_BOLD).fontSize(8.5).fillColor(COLORS.muted).text(label.toUpperCase(), { width })
  doc.font(FONT_REGULAR).fontSize(10).fillColor(COLORS.ink).text(text, { width })
  doc.moveDown(0.5)
}

// A simple two-column row (label left, figures right), used for the
// per-period and per-category breakdown tables. Not a real table grid -
// pdfkit has no table primitive, and this report has few enough rows that a
// grid would be more code than it is worth.
function tableRow(doc, left, right) {
  const width = contentWidth(doc)
  const rightWidth = width * 0.45
  const leftWidth = width - rightWidth

  ensureRoom(doc, 18)
  const y = doc.y
  doc.font(FONT_REGULAR).fontSize(9.5).fillColor(COLORS.ink).text(left, doc.page.margins.left, y, { width: leftWidth })
  doc
    .font(FONT_REGULAR)
    .fontSize(9.5)
    .fillColor(COLORS.muted)
    .text(right, doc.page.margins.left + leftWidth, y, { width: rightWidth, align: 'right' })
  doc.moveDown(0.35)
}

function drawCoverPage(doc, { report }) {
  const width = contentWidth(doc)

  doc.moveDown(2.2)
  doc
    .font(FONT_BOLD)
    .fontSize(10)
    .fillColor(COLORS.classification)
    .text(CLASSIFICATION_BANNER, { align: 'center', width })
  doc.moveDown(2.4)

  doc.font(FONT_BOLD).fontSize(21).fillColor(COLORS.ink).text(report.companyName || 'Rectifia', { align: 'center', width })
  doc.moveDown(0.3)
  doc
    .font(FONT_REGULAR)
    .fontSize(13)
    .fillColor(COLORS.muted)
    .text('Board & Audit Compliance Summary', { align: 'center', width })
  doc.moveDown(2.6)

  const rows = [
    ['Reporting Period', `${report.range.startPeriod} to ${report.range.endPeriod}`],
    ['Total Case Volume', String(report.totals.caseCount)],
    ['Generated', formatTimestamp(report.generatedAt)],
    ['Generated by', report.generatedByLabel || 'Unknown'],
  ]
  rows.forEach(([label, value]) => {
    doc.font(FONT_BOLD).fontSize(9).fillColor(COLORS.muted).text(label, { width })
    doc.font(FONT_REGULAR).fontSize(11).fillColor(COLORS.ink).text(value ?? '-', { width })
    doc.moveDown(0.55)
  })

  doc.moveDown(1)
  doc
    .font(FONT_ITALIC)
    .fontSize(9)
    .fillColor(COLORS.muted)
    .text(
      'Every figure in this document is an aggregate or a rate computed over multiple cases. No case narrative, questionnaire response, message, or individually attributable score is included anywhere in this report. Category and department breakdowns below the reporting threshold are withheld rather than shown as a small number.',
      { width }
    )
}

function drawVolumeSection(doc, report) {
  sectionHeading(doc, '1. Case Volume Summary')
  keyValue(doc, 'Total cases in range', report.totals.caseCount)

  doc.font(FONT_BOLD).fontSize(9.5).fillColor(COLORS.ink).text('By category')
  doc.moveDown(0.3)
  const categoryEntries = Object.entries(report.totals.volumeByCategory)
  if (categoryEntries.length === 0) {
    emptyState(doc, 'No category reached the minimum reporting threshold in this range.')
  } else {
    categoryEntries.forEach(([category, count]) => tableRow(doc, humanize(category), String(count)))
  }

  doc.moveDown(0.4)
  doc.font(FONT_BOLD).fontSize(9.5).fillColor(COLORS.ink).text('By department')
  doc.moveDown(0.3)
  const departmentEntries = Object.entries(report.totals.volumeByDepartment)
  if (departmentEntries.length === 0) {
    emptyState(doc, 'No department reached the minimum reporting threshold in this range.')
  } else {
    departmentEntries.forEach(([department, count]) => tableRow(doc, humanize(department), String(count)))
  }
}

function drawResolutionSection(doc, report) {
  sectionHeading(doc, '2. Time to Resolution')
  doc
    .font(FONT_ITALIC)
    .fontSize(8.5)
    .fillColor(COLORS.muted)
    .text('Average days from case creation to closure, by reporting period. A period with fewer than the reporting threshold of closed cases shows no figure.', {
      width: contentWidth(doc),
    })
  doc.moveDown(0.4)

  report.trend.forEach((period) => {
    tableRow(
      doc,
      period.period,
      period.avgResolutionDays == null ? 'insufficient data' : `${period.avgResolutionDays} days avg`
    )
  })
}

function drawComplianceSection(doc, report) {
  sectionHeading(doc, '3. Compliance Deadline Hit Rate')
  const rule = report.trend.find((p) => p.compliance)?.compliance
  if (rule) {
    keyValue(doc, 'Rule Applied', rule.ruleLabel)
    keyValue(doc, 'Acknowledgment Window', `${rule.acknowledgmentDueDays} days`)
    keyValue(doc, 'Feedback / Resolution Window', `${rule.feedbackDueDays} days`)
  }
  doc.moveDown(0.3)

  report.trend.forEach((period) => {
    const c = period.compliance
    tableRow(
      doc,
      `${period.period} - acknowledged in window`,
      c.acknowledgmentSampleSize > 0 ? `${formatPercent(c.acknowledgedWithinWindowRate)} (n=${c.acknowledgmentSampleSize})` : 'no data'
    )
    tableRow(
      doc,
      `${period.period} - resolved in window`,
      c.resolutionSampleSize > 0 ? `${formatPercent(c.resolvedWithinWindowRate)} (n=${c.resolutionSampleSize})` : 'no data'
    )
  })
}

function drawConsistencySection(doc, report) {
  sectionHeading(doc, '4. Consistency Engine Flag Summary')
  doc
    .font(FONT_ITALIC)
    .fontSize(8.5)
    .fillColor(COLORS.muted)
    .text(
      'Whether this company’s own closed-case outcomes for similar cases have historically been harsher, more lenient, or consistent with each other. Computed only against this company’s own case history - no cross-company comparison.',
      { width: contentWidth(doc) }
    )
  doc.moveDown(0.4)

  const entries = Object.entries(report.consistency.byCategory || {})
  if (entries.length === 0) {
    emptyState(doc, 'No consistency data available.')
    return
  }

  entries.forEach(([category, summary]) => {
    ensureRoom(doc, 60)
    doc.font(FONT_BOLD).fontSize(10).fillColor(COLORS.ink).text(humanize(category))
    doc.moveDown(0.2)
    if (summary.status === 'insufficient_data') {
      emptyState(doc, `Insufficient data - fewer closed reference cases than the reporting minimum (${summary.referenceCaseCount} on file).`)
      return
    }
    tableRow(doc, 'Reference cases on file', String(summary.referenceCaseCount))
    tableRow(doc, 'Consistent with typical action', String(summary.consistentCount))
    tableRow(doc, 'Harsher than typical', String(summary.harsherCount))
    tableRow(doc, 'More lenient than typical', String(summary.lenientCount))
    doc.moveDown(0.3)
  })
}

function drawFooter(doc, { pageNumber, pageCount }) {
  const left = doc.page.margins.left
  const right = doc.page.margins.right
  const width = doc.page.width - left - right
  const footerTop = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT

  doc.moveTo(left, footerTop).lineTo(doc.page.width - right, footerTop).strokeColor(COLORS.line).lineWidth(0.5).stroke()
  doc
    .font(FONT_BOLD)
    .fontSize(7.5)
    .fillColor(COLORS.classification)
    .text(CLASSIFICATION_BANNER, left, footerTop + 7, { width, align: 'center' })
  doc
    .font(FONT_REGULAR)
    .fontSize(7.5)
    .fillColor(COLORS.muted)
    .text(`Page ${pageNumber} of ${pageCount}`, left, footerTop + 18, { width, align: 'right' })
}

// Renders the compliance/analytics summary as PDF bytes. Takes exactly the
// aggregate object exportComplianceReport.js compiles from companies/
// {companyId}/analytics/* - never a case document, never anything from
// caseMetadata or referenceCases beyond what that module already aggregated.
// Resolves { buffer, pageCount }, the same shape renderReportPdf.js returns.
async function renderComplianceReportPdf(report) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: PAGE_MARGIN, bottom: PAGE_MARGIN + FOOTER_HEIGHT, left: PAGE_MARGIN, right: PAGE_MARGIN },
        bufferPages: true,
        info: {
          Title: `${report.companyName || 'Rectifia'} - Compliance Summary (${report.range.startPeriod} to ${report.range.endPeriod})`,
          Subject: CLASSIFICATION_BANNER,
          Author: report.companyName || 'Rectifia',
        },
      })

      const chunks = []
      let pageCount = 0
      doc.on('data', (chunk) => chunks.push(chunk))
      doc.on('end', () => resolve({ buffer: Buffer.concat(chunks), pageCount }))
      doc.on('error', reject)

      doc.font(FONT_REGULAR)
      drawCoverPage(doc, { report })

      doc.addPage()
      drawVolumeSection(doc, report)
      drawResolutionSection(doc, report)
      drawComplianceSection(doc, report)
      drawConsistencySection(doc, report)

      const range = doc.bufferedPageRange()
      pageCount = range.count
      for (let i = range.start; i < range.start + range.count; i += 1) {
        doc.switchToPage(i)
        const savedBottom = doc.page.margins.bottom
        doc.page.margins.bottom = 0
        drawFooter(doc, { pageNumber: i - range.start + 1, pageCount: range.count })
        doc.page.margins.bottom = savedBottom
      }

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}

module.exports = { renderComplianceReportPdf, CLASSIFICATION_BANNER }
