import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { verifyInviteCode, acceptInvite, signIn, markInviteAccepted } from '../services/authService'

// :token is the oobCode from the invite link generated by inviteStaff.js
// (admin.auth().generatePasswordResetLink). Firebase itself rejects an
// expired or already-used code, so that's what drives the error state below
// rather than a separate Firestore "used" lookup.
function AcceptInvitePage() {
  const { token } = useParams()
  const navigate = useNavigate()
  const [email, setEmail] = useState(null)
  const [checking, setChecking] = useState(true)
  const [tokenError, setTokenError] = useState(null)
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [formError, setFormError] = useState(null)

  useEffect(() => {
    let cancelled = false
    async function checkToken() {
      try {
        const invitedEmail = await verifyInviteCode(token)
        if (!cancelled) setEmail(invitedEmail)
      } catch (err) {
        if (!cancelled) {
          setTokenError(
            err.code === 'auth/expired-action-code' || err.code === 'auth/invalid-action-code'
              ? 'This invite link has expired or has already been used. Ask your Company Admin to send a new one.'
              : 'This invite link is not valid.'
          )
        }
      } finally {
        if (!cancelled) setChecking(false)
      }
    }
    checkToken()
    return () => {
      cancelled = true
    }
  }, [token])

  async function handleSubmit(e) {
    e.preventDefault()
    setFormError(null)
    if (password.length < 8) {
      setFormError('Password must be at least 8 characters')
      return
    }
    if (password !== confirmPassword) {
      setFormError('Passwords do not match')
      return
    }
    setSubmitting(true)
    try {
      await acceptInvite(token, password)
      // Invites only ever create company staff (never a super admin - that
      // account type is created directly by Lumora), so this always lands
      // on the staff dashboard.
      await signIn(email, password)
      await markInviteAccepted()
      navigate('/dashboard', { replace: true })
    } catch (err) {
      setFormError('Could not set your password. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  if (checking) {
    return (
      <div className="mx-auto flex max-w-4xl flex-col gap-8 p-6">
        <p className="text-sm text-muted">Checking your invite...</p>
      </div>
    )
  }

  if (tokenError) {
    return (
      <div className="mx-auto flex max-w-4xl flex-col gap-8 p-6">
        <div className="flex flex-col gap-3 rounded-lg border border-line bg-surface p-4">
          <h1 className="text-xl font-semibold">Invite not available</h1>
          <p className="text-sm text-critical">{tokenError}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="flex min-h-screen items-center justify-center p-6">
      <div className="flex w-full max-w-md flex-col gap-3">
        <div className="flex items-center gap-2">
          <span className="h-5 w-1.5 rounded-full bg-gold" aria-hidden="true" />
          <span className="text-lg font-semibold tracking-tight text-navy">Rectifia</span>
        </div>
        <h1 className="text-xl font-semibold">Set up your account</h1>

        <form onSubmit={handleSubmit} className="flex flex-col gap-3 rounded-lg border border-line bg-surface p-4">
          <input
            type="email"
            value={email}
            readOnly
            disabled
            className="rounded border border-line bg-canvas px-3 py-2 text-sm text-muted"
          />
          <input
            type="password"
            required
            placeholder="Choose a password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="field rounded px-3 py-2 text-sm"
          />
          <input
            type="password"
            required
            placeholder="Confirm password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            className="field rounded px-3 py-2 text-sm"
          />

          {formError && <p className="text-sm text-critical">{formError}</p>}

          <button
            type="submit"
            disabled={submitting}
            className="btn-primary rounded px-4 py-2 text-sm font-medium disabled:opacity-50"
          >
            {submitting ? 'Setting up...' : 'Set password and continue'}
          </button>
        </form>
      </div>
    </div>
  )
}

export default AcceptInvitePage
