import { useEffect, useState } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { verifyInviteCode, acceptInvite, signIn, markInviteAccepted } from '../services/authService'
import AuthLayout from '../components/shared/AuthLayout'
import Alert from '../components/ui/Alert'
import Button from '../components/ui/Button'
import { Input } from '../components/ui/Field'
import { FullPageLoader } from '../components/ui/Loading'

// :token is the oobCode from the invite link generated by inviteStaff.js
// (admin.auth().generatePasswordResetLink). Firebase itself rejects an
// expired or already-used code, so that's what drives the error state below
// rather than a separate Firestore "used" lookup.
function AcceptInvitePage() {
  const { t } = useTranslation()
  const { token } = useParams()
  const navigate = useNavigate()
  const [email, setEmail] = useState(null)
  const [checking, setChecking] = useState(true)
  const [tokenError, setTokenError] = useState(null)
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [formError, setFormError] = useState(null)

  useEffect(() => {
    let cancelled = false
    async function checkToken() {
      try {
        const invitedEmail = await verifyInviteCode(token)
        if (!cancelled) setEmail(invitedEmail)
      } catch (err) {
        if (!cancelled) {
          setTokenError(
            err.code === 'auth/expired-action-code' || err.code === 'auth/invalid-action-code'
              ? t('acceptInvite.errors.expired')
              : t('acceptInvite.errors.invalid')
          )
        }
      } finally {
        if (!cancelled) setChecking(false)
      }
    }
    checkToken()
    return () => {
      cancelled = true
    }
  }, [token, t])

  async function handleSubmit(e) {
    e.preventDefault()
    setFormError(null)
    if (password.length < 8) {
      setFormError(t('acceptInvite.errors.tooShort'))
      return
    }
    if (password !== confirmPassword) {
      setFormError(t('acceptInvite.errors.mismatch'))
      return
    }
    setSubmitting(true)
    try {
      await acceptInvite(token, password)
      // Invites create both company staff and Company Admins (never a super
      // admin - that account type is created directly by Lumora), so this
      // hands off to RootRedirect via "/" rather than a hardcoded route -
      // it already knows a Company Admin belongs on /admin/overview and
      // everyone else on /dashboard.
      await signIn(email, password)
      await markInviteAccepted()
      navigate('/', { replace: true })
    } catch {
      setFormError(t('acceptInvite.errors.setPasswordFailed'))
    } finally {
      setSubmitting(false)
    }
  }

  if (checking) {
    return <FullPageLoader label={t('acceptInvite.checking')} />
  }

  if (tokenError) {
    return (
      <AuthLayout
        title={t('acceptInvite.notAvailable.title')}
        footer={
          <Link to="/login" className="font-medium text-navy hover:underline">
            {t('acceptInvite.notAvailable.goToSignIn')}
          </Link>
        }
      >
        <Alert variant="error" title={t('acceptInvite.notAvailable.alertTitle')}>
          {tokenError}
        </Alert>
      </AuthLayout>
    )
  }

  return (
    <AuthLayout
      title={t('acceptInvite.title')}
      description={t('acceptInvite.description')}
    >
      <form onSubmit={handleSubmit} className="card flex flex-col gap-4 p-6">
        <Input label={t('acceptInvite.yourEmail')} type="email" value={email ?? ''} readOnly disabled />
        <Input
          label={t('acceptInvite.choosePassword')}
          type="password"
          required
          autoComplete="new-password"
          placeholder={t('acceptInvite.atLeast8')}
          hint={t('acceptInvite.hint')}
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <Input
          label={t('acceptInvite.confirmPassword')}
          type="password"
          required
          autoComplete="new-password"
          placeholder={t('acceptInvite.reEnter')}
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
        />

        {formError && <Alert variant="error">{formError}</Alert>}

        <Button
          type="submit"
          variant="primary"
          size="lg"
          className="w-full"
          loading={submitting}
          loadingLabel={t('acceptInvite.settingUp')}
        >
          {t('acceptInvite.setPasswordAndContinue')}
        </Button>
      </form>
    </AuthLayout>
  )
}

export default AcceptInvitePage
